### ISSUE TITLE
kernel cmd line missing rootwait

### ISSUE THREAD

**Issue by pedwo** [cmhe/meta-readonly-rootfs-overlay#1]
Hi,
Minor point, you need rootwait in the kernel cmd line to be robust.
Thanks!

**Comment by cmhe** [comment]
Thanks for opening that issue, pedwo.

Maybe I misunderstand you, but rootwait is handled by the kernel.
So AFAIK this has nothing to do with the initscript in this repo.

**Comment by pedwo** [comment]
The issue concerns your README.md, see https://github.com/cmhe/meta-readonly-rootfs-overlay#kernel-command-line-parameters

**Comment by cmhe** [comment]
The instructions in the readme are not meant as a complete examples of the kernel command line.
