### ISSUE TITLE
Can't use jffs2 for rw filesyste,

### ISSUE THREAD

**Issue by pedwo** [cmhe/meta-readonly-rootfs-overlay#2]
Hi,

I tried using your layer with a JFFS2 rw filesystem, however it fails because you have to specify the filesystem type when mounting JFFS2 (i.e. "mount -t jffs2 ...").

Thanks
Phil

**Comment by pedwo** [comment]
Also you can't specify "mode=755" when mounting JFFS2.

**Comment by cmhe** [comment]
Ok, will fix that later.
I plan of making all mount parameters overwriteable via cmdline.

**Comment by cmhe** [comment]
I pushed this to 3886705680f0f0e1fccaa68229597878fa2ce7a3.
Since I don't currently use this, I have not tested it. So testing and a review is welcome.
